### PR TITLE
Store profile selection mode in a separate file

### PR DESCRIPTION
**Pull request by olysonek**
The profile selection mode is now written to /etc/tuned/profile_mode
instead of the second line of /etc/tuned/active_profile.

Here are the rules for interpreting the contents of the files. If
either of the files does not exist, it is treated the same as if
it were empty.

If active_profile is empty:
    If profile_mode contains 'manual':
        Manual mode, no profile will be used, tuned will run without a profile
    else if profile_mode is empty or contains 'auto':
        Automatic mode, recommended profile is used
    else:
        Error
else:
    If profile_mode contains 'manual', or is empty (for compatibility reasons):
        Manual mode, the profile in active_profile will be used
    else if profile_mode contains 'auto':
        Automatic mode, recommended profile is used
    else:
        Error

Resolves: https://github.com/redhat-performance/tuned/issues/64

Signed-off-by: Ondřej Lysoněk <olysonek@redhat.com>

### CODE REVIEW

**Comment by olysonek** [comment]
Hrmm, see the commit message if you want it displayed properly :).

**Comment by yarda** [comment]
Please also update the spec file - add there profile_mode

**Comment by olysonek** [comment]
Done

**Comment by yarda** [comment]
Thanks, merged.

**Pull request merged**
