### PR TITLE
Fix improper parsing of include directive

### PR DESCRIPTION
**Pull request by jmencak**
Resolves rhbz#2017924

Signed-off-by: Jiri Mencak <jmencak@users.noreply.github.com>

### CODE REVIEW

**Review by yarda — CHANGES_REQUESTED** [review]
This adds the space as the allowed delimiter which is change of the behavior, i.e.:
`profile1 profile2` is now parsed as two profiles: profile1, profile2 and not as one profile "profile1 profile2".

**Comment by jmencak** [comment]
> This adds the space as the allowed delimiter which is change of the behavior, i.e.: `profile1 profile2` is now parsed as two profiles: profile1, profile2 and not as one profile "profile1 profile2".

Thank you for the review, @yarda!  Hopefully, we'll never see profile names with whitespace in them unless they're in built-ins.   In any case, fixed, but still not bullet-proof.  A much better fix would be a proper parser to take things such as built-ins into account.  We can hopefully leave this as future work...

**Comment by yarda** [comment]
> Thank you for the review, @yarda! Hopefully, we'll never see profile names with whitespace in them unless they're in built-ins. In any case, fixed, but still not bullet-proof. A much better fix would be a proper parser to take things such as built-ins into account. We can hopefully leave this as future work...

Wouldn't just dropping the '\b' from the original code do the same?

**Comment by jmencak** [comment]
> Wouldn't just dropping the '\b' from the original code do the same?

Actually, it would.  Thanks for pointing it out.  I wasn't aware leading/trailing spaces were already being stripped.

**Review by yarda — APPROVED** [review]

**Pull request merged**
