### PR TITLE
Add support for config options hints and fix running under normal user

### PR DESCRIPTION
**Pull request by TomasKorbar**
Hi,
this pullrequest:
- simplyfies tuned-gui code
- adds support for config options hints
- fixes running under normal user without using xserver

### CODE REVIEW

**Comment by yarda** [comment]
Thanks, merged.

**Comment by TomasKorbar** [comment]
Yes you are right. I also accidentally forgot `import inspect` in tuned-gui.py imports. Should i provide another pullrequest to solve this?

**Comment by olysonek** [comment]
Please, do.

**Comment by olysonek** [comment]
FYI, we added contribution guidelines to Tuned a couple of days ago ;).
https://github.com/redhat-performance/tuned/blob/master/CONTRIBUTING.md

**Comment by TomasKorbar** [comment]
Yes i have noticed new guidelines. From now on my contributions will conform to them :)

**Pull request merged**
