### PR TITLE
scheduler: new option cgroup_ps_blacklist

### PR DESCRIPTION
**Pull request by yarda**
This option allows skipping processes belonging to the blacklisted
cgroups. It matches the regular expression against items from the
/proc/PID/cgroups. Items/lines from the /proc/PID/cgroups are separated
by commas ','. Each item consists of the:
hierarchy-ID:controller-list:cgroup-path

Example of the content on which the regular expression is run:
10:hugetlb:/,9:perf_event:/,8:blkio:/

For cgroups v2 the hierarchy-ID is 0 and the controller-list is ''.
For details see man cgroups.7. The only difference from the man
cgroups.7 is that it uses commas for separation of the items instead
of the new lines.

Multiple regular expressions can be separated by the semicolon ';'.

Examples:
[scheduler]
isolated_cores=1
cgroup_ps_blacklist=\b/daemons\b

It will move all processes away from the core 1 except processes which
belongs to the cgroup '/daemons'. The '\b' is regular expression
metacharacter that matches word boundary (i.e. it matches only
'/daemons', not e.g. '/daemonset' or '/group/daemons'). In this example
we do not care about the hierarchy-ID and the controller-list.

[scheduler]
isolated_cores=1
cgroup_ps_blacklist=\b8:blkio:/\b

In this example it skips processes belonging to the cgroup '/',
with hierarchy-ID 8 and controller-list blkio.

[scheduler]
isolated_cores=1
cgroup_ps_blacklist=\b/daemons\b;\b/test\b

In this example two regular expressions are used which tries to match
'/daemons' and '/test' cgroup-path. If either matches (i.e. the OR operator),
the process is skipped (i.e. not moved away from the core 1).

Resolves: rhbz#1980715

Signed-off-by: Jaroslav Škarvada <jskarvad@redhat.com>

### CODE REVIEW

**Comment by jmencak** [comment]
Many thanks for this PR, @yarda !  I'll be reviewing and testing this today.  Do we also want something like `cgroup_ps_whitelist` to be consistent with `ps_whitelist`?

**Comment by yarda** [comment]
> Many thanks for this PR, @yarda ! I'll be reviewing and testing this today. Do we also want something like `cgroup_ps_whitelist` to be consistent with `ps_whitelist`?

I think it is needed only in case there is a need for features/options to be orthogonal. The whitelist feature will have some overhead (especially if we will add later support for the runtime processing through the perf). With the blacklist there is just the check if the regex is not empty, process it, otherwise skip. I.e. nearly no overhead if the feature is not used. With the whitelist it will have to match the regex all the time (or we could add some optimization to skip the check in the case the regex is '.*'). And if you want to pin just some cgroups to some cpuset, you can do it directly through the cgroups (or through the cgroups feature of TuneD).

**Comment by jmencak** [comment]
I've tested this PR and it works for both cgroup v1 and v2.  It also solves my usecase and I can confirm it solves rhbz#1980715. The `cgroup_ps_whitelist` would be nice-to-have, however, at the moment I do not see any real need for implementing it at this point.  The only concern I had was the separation cgroup hierarchies from the /proc/PID/cgroups by '',", as the same separator is used by the controller-list (hierarchy-ID:controller-list:cgroup-path, e.g. 5:cpuacct,cpu,cpuset:/daemons in cgroup v1) and that might make regular expression matching a bit trickier.  Nevertheless, I believe these are minor concerns and unless @CZerta has any objections, I believe this PR is good to go.  Thanks @yarda !

**Comment by CZerta** [comment]
@jmencak Did you try regexps with '\b' symbol? It seams it does not work for me, rest LGTM

**Comment by jmencak** [comment]
> @jmencak Did you try regexps with '\b' symbol? It seams it does not work for me, rest LGTM

Yeah, the example `cgroup_ps_blacklist=\b/daemons\b;\b/test\b` is a bit misleading and needs fixed.  I think you want something like:
`cgroup_ps_blacklist=\bdaemons\b;\btest\b` instead (/cc @yarda).  Then it works.

**Review by CZerta — APPROVED** [review]
Silly me. LGTM

**Comment by MarSik** [comment]
Folks? I see this was approved 7 days ago, how can we unblock the merge?

**Comment by jmencak** [comment]
From my perspective we can merge this after @yarda fixes the commit message as the examples with '\b' don't quite work.  See [my docs of this functionality](https://github.com/redhat-performance/tuned/pull/337/commits/ce23791eb1be350d2fc983d28dc5e0143951a908) that hopefully should work.

**Comment by yarda** [comment]
> Folks? I see this was approved 7 days ago, how can we unblock the merge?

We had feature freeze between 2.16.0 RC and stable (which was released yesterday). AFAIK @jmencak is cherry picking patches he is interested in, so it shouldn't block him.

**Comment by jmencak** [comment]
> > Folks? I see this was approved 7 days ago, how can we unblock the merge?
> 
> We had feature freeze between 2.16.0 RC and stable (which was released yesterday). AFAIK @jmencak is cherry picking patches he is interested in, so it shouldn't block him.

Well, yes and no.  I cherry-pick stuff that *merged* upstream as until the stuff merges there's actually no guaranteed it will merge. :)

**Comment by yarda** [comment]
Rebased and updated the commit message.

**Comment by jmencak** [comment]
> Rebased and updated the commit message.

Thanks for the effort, Jardo, but I think it is still not quite right.  `\b` matches word boundaries, so `/\b` in will not work in `cgroup_ps_blacklist=\b8:blkio:/\b`.  Example:

```
$ echo '10:hugetlb:/,9:perf_event:/,8:blkio:/,7:st_else:/' | grep -P '\b8:blkio:/\b'
$ echo '10:hugetlb:/,9:perf_event:/,8:blkio:/,7:st_else:/' | grep -P '\b8:blkio:/,'
10:hugetlb:/,9:perf_event:/,8:blkio:/,7:st_else:/
```

Also, I believe the description in the PR should also be probably adjusted so that people blindly copy&pasting from PRs are not bit by this.

**Comment by yarda** [comment]
> > Rebased and updated the commit message.
> 
> Thanks for the effort, Jardo, but I think it is still not quite right. `\b` matches word boundaries, so `/\b` in will not work in `cgroup_ps_blacklist=\b8:blkio:/\b`. Example:
> 
> ```
> $ echo '10:hugetlb:/,9:perf_event:/,8:blkio:/,7:st_else:/' | grep -P '\b8:blkio:/\b'
> $ echo '10:hugetlb:/,9:perf_event:/,8:blkio:/,7:st_else:/' | grep -P '\b8:blkio:/,'
> 10:hugetlb:/,9:perf_event:/,8:blkio:/,7:st_else:/
> ```
> 
> Also, I believe the description in the PR should also be probably adjusted so that people blindly copy&pasting from PRs are not bit by this.

Good catch, check now.

**Comment by jmencak** [comment]
This will work, many thanks!
/lgtm

**Pull request merged**
