### PR TITLE
Support for adjusting netdev queue count

### PR DESCRIPTION
**Pull request by niteshnarayanlal**
Following patch-set enables tuned to adjust the queue count for
each network device via tuned configuration file. This functionality is
implemented by integrating the ethtool channels control feature with tuned.

This support is essentially required for the real-time setup that has
several isolated but very few housekeeping CPUs. In such environments, it
has been observed that the housekeeping CPUs often run out of vectors when
the IRQs are moved from isolated to housekeeping CPUs. This primarily
happens due to a large number of queues (hence IRQs) creation for each
network device based on all available online CPUs.

With this support added tuned can be configured to adjust the queue count
based on the housekeeping CPUs.

Changelog from v1[1]:
- Replaced get_queue_count with check_net_queue_count based on Jaroslav's suggestion.
- Fixed Inconsitent whitespaces, tabs/spaces.

[1] https://github.com/redhat-performance/tuned/pull/314

Nitesh Narayan Lal (2):
plugin_net: Implement setting 'channels' parameters
realtime: added support for netdev_queue_count

profiles/realtime/realtime-variables.conf | 8 +++
profiles/realtime/tuned.conf | 3 ++
tuned/plugins/plugin_net.py | 50 +++++++++++++++++--
.../functions/function_get_queue_count.py | 23 +++++++++
4 files changed, 80 insertions(+), 4 deletions(-)
create mode 100644 tuned/profiles/functions/function_get_queue_count.py

### CODE REVIEW

**Comment by niteshnarayanlal** [comment]
@yarda should I send this patch-set on the mailing list as well?

**Comment by yarda** [comment]
> @yarda should I send this patch-set on the mailing list as well?

@niteshnarayanlal it's not needed to send it to our mailing list, just the PR is OK.

**Comment by yanirq** [comment]
@yarda  can we invoke the PR's testing scheme ? 

@niteshnarayanlal  I will test this locally and have a review to prompt for a final ACK.

**Comment by niteshnarayanlal** [comment]
> @yarda can we invoke the PR's testing scheme ?
> 
> @niteshnarayanlal I will test this locally and have a review to prompt for a final ACK.

Sure, thanks.

> Also, will #314 become obsolete after this patch ?

Yes, that is correct. I can go ahead and close that PR.

**Comment by yanirq** [comment]
P.S  , this should have additional review from tuned maintainers

**Comment by niteshnarayanlal** [comment]
> P.S , this should have additional review from tuned maintainers

Sure, I have also posted the PR link to the mailing list.
Please let me know if anything else is required from my end.

**Comment by MarSik** [comment]
Hi all, is there any progress since last week?

@yarda Can you give this another look please?

**Comment by yarda** [comment]
LGTM, merging.

**Pull request merged**
