### PR TITLE
Enable copr builds and add packit config

### PR DESCRIPTION
**Pull request by dhodovsk**
Let us introduce [packit service](https://packit.dev) to you - the automation to integrate upstream open source projects into Fedora operating system.

After merging this PR, you are just a few steps away from RPM builds being automatically triggered on your PR's.
It means, that you'll be able to try and play with your change, packaged as an RPM.

But there is more. By using packit, you can for example enable adding new releases into Fedora Rawhide.

What are the next steps?
* Install [Packit-as-a-Service github application](https://github.com/marketplace/packit-as-a-service) in your repo
* In case you are first user, wait for account approval
* Enjoy the built RPMs!

For more info, please:
 * check out the documentation: https://packit.dev/docs/
 * contact @packit-service

### CODE REVIEW

**Comment by yarda** [comment]
@dhodovsk thanks, but:
- we currently cannot install the Packit app, because this is organization account, not personal account, we are trying to resolve it on the organizational level
- I think we currently don't want to sync the upstream spec file to the Fedora, could you please edit the PR for Packit not to do it?

**Comment by yarda** [comment]
Packit app should be deployed now.

**Comment by dhodovsk** [comment]
The syncing to fedora is not turned on in this config, for enabling it this should be added: 
```
jobs:
- job: sync_from_downstream
  trigger: commit
```
But with the configuration, as it is now, you are able to propose to downstream with using packit CLI tool.

I agree that it is unfortunate, having all these data required in packit.yaml. We aim to minimalize it as possible in the near future (for example [here](https://github.com/packit-service/packit/issues/140))

**Comment by yarda** [comment]
> The syncing to fedora is not turned on in this config, for enabling it this should be added:
> 
> ```
> jobs:
> - job: sync_from_downstream
>   trigger: commit
> ```
> 
> But with the configuration, as it is now, you are able to propose to downstream with using packit CLI tool.
> 
> I agree that it is unfortunate, having all these data required in packit.yaml. We aim to minimalize it as possible in the near future (for example [here](https://github.com/packit-service/packit/issues/140))

@dhodovsk thanks. From the project docs the current behaviour wasn't clear to me, so it's probably OK now, so merging.

**Pull request merged**
