### PR TITLE
Remove obsolete rhts imports from beakerlib tests

### PR DESCRIPTION
**Pull request by psss**
I would recommend to get rid of the old rhts imports as well.

### CODE REVIEW

**Comment by psss** [comment]
@TomasTomecek, interesting, packit shows congratulations but copr is still building:

    running
    running
    succeeded
    succeeded

This causes subsequent failure of the testing as well.

**Comment by yarda** [comment]
Thanks, merging. But it seems it's still failing when installing beakerlib:
`[12:29:43] [E] Pipeline reported an exception in module 'cruncher': Command 'cd ~/git-source; dnf -y install beakerlib git' failed with return code '255' `

**Comment by yarda** [comment]
@psss or 

> Thanks, merging. But it seems it's still failing when installing beakerlib:
> `[12:29:43] [E] Pipeline reported an exception in module 'cruncher': Command 'cd ~/git-source; dnf -y install beakerlib git' failed with return code '255' `

@psss or @TomasTomecek any idea who to contact about it?

**Comment by psss** [comment]
I believe the problem above is caused by Packit reporting success too early. Cruncher is then started before the copr builds are finished. @TomasTomecek, is that a known issue?

**Comment by jpopelka** [comment]
Ok, I'll take a look.

**Comment by jpopelka** [comment]
I've just reverted some changes I did earlier today, let me know how it looks like now.

**Comment by yarda** [comment]
> /packit copr-build

It probably needs new PR :)

**Comment by jpopelka** [comment]
As Tomas pointed out in IRC the know issue is https://github.com/packit-service/packit-service/issues/201

I'm re-reverting my changes :-)

**Pull request merged**
