### PR TITLE
RHEL-3707: Add support for sysctl names with slash

### PR DESCRIPTION
**Pull request by MarSik**
The logic for converting sysctl name to path did not work for sysctls like:

[sysctl]
net.ipv4.conf.bond0/355.forwarding=1

### CODE REVIEW

**Comment by yarda** [comment]
Hmm, it seems like a side-effect of the sysctl tool internal conversions, but we should follow its behaviour.

I don't like the triple replacement with internal escaping, what about the following maybe more python way which should be more "bullet-proof"?:
```
try:
  trans = str.maketrans("./", "/.")
except AttributeError:
  import string
  trans = string.maketrans("./", "/.")
return "/proc/sys/%s" % option.translate(trans)
```
The exception handler is there to also support python2 :) otherwise it's one-liner.

Or maybe we could add the 'tr' command to the the utils/commands.py doing all the magic and then just:
```
return "/proc/sys/%s" % self._cmd.tr(option, "./", "/.")
```

**Comment by MarSik** [comment]
Translate works for me. I agree it is better, I simply did not know the function so thanks for teaching me something new :)

**Comment by zacikpa** [comment]
@MarSik I pushed the change proposed by @yarda into your branch, hope you don't mind :)

**Comment by zacikpa** [comment]
Sorry for the many force pushes :)

I updated the code and the commit message according to your comments @yarda. To be able to use `_cmd ` in the function, I had to make it (and others) a class method, so I created a separate commit for that. Let me know if you want that squashed as well.

**Comment by yarda** [comment]
> Sorry for the many force pushes :)
> 
> I updated the code and the commit message according to your comments @yarda. To be able to use `_cmd ` in the function, I had to make it (and others) a class method, so I created a separate commit for that. Let me know if you want that squashed as well.

NP, thanks for the cleanup. I think here it makes sense to have two commits.

**Comment by yarda** [comment]
LGTM, thanks.

**Pull request merged**
