### PR TITLE
Profile migration fix

### LINKED ISSUE #642: profile scripts try to load /usr/lib/tuned/functions but it has been moved
Ohai,

as part of 6d3aa949b3a7019bbb70f9bd3b34cb4a9381e8fb the `/usr/lib/tuned/functions` file was moved to `/usr/lib/tuned/profiles/functions`, however, several places still reference the old path:

```
% git grep tuned/functions
doc/manual/modules/performance/ref_available-tuned-plug-ins.adoc:Bash scripts can import the [filename]`/usr/lib/tuned/functions` Bash library and use the functions defined there. Use these functions only for functionality that is not natively provided by *TuneD*. If a function name starts with an underscore, such as `_wifi_set_power_level`, consider the function private and do not use it in your scripts, because it might change in the future.
experiments/powertop2tuned.py:. /usr/lib/tuned/functions
profiles/cpu-partitioning/script.sh:. /usr/lib/tuned/functions
profiles/laptop-ac-powersave/script.sh:. /usr/lib/tuned/functions
profiles/powersave/script.sh:. /usr/lib/tuned/functions
profiles/realtime-virtual-guest/script.sh:. /usr/lib/tuned/functions
profiles/realtime-virtual-host/script.sh:. /usr/lib/tuned/functions
profiles/realtime/script.sh:. /usr/lib/tuned/functions
profiles/spindown-disk/script.sh:. /usr/lib/tuned/functions
tuned/plugins/plugin_script.py:        Bash scripts can import the [filename]`/usr/lib/tuned/functions`
```

I am not sure which one is the correct place, but the current state is certainly not correct ;-)

### PR DESCRIPTION
**Pull request by zacikpa**
In #615,  the installation directory for `functions` (containing bash functions used by profile scripts) and `recommend.d` was accidentally changed to `usr/lib/tuned/profiles/`, where all profiles were migrated.

This also changes the location of `functions` file within the repository, separating it from the profiles themselves.

Resolves #642.

### CODE REVIEW

**Review by evgeni — APPROVED** [review]
This fixes my Debian builds where the original movement problems were found :)

**Comment by yarda** [comment]
Thanks, LGTM.

**Comment by jmencak** [comment]
This breaks the build on my system.  I'm getting:

```
install -Dpm 0644 modules.conf /root/rpmbuild/BUILDROOT/tuned-2.23.0-1.el9.x86_64/etc/modprobe.d/tuned.conf
# profiles & system config
cp -a profiles/* /root/rpmbuild/BUILDROOT/tuned-2.23.0-1.el9.x86_64/usr/lib/tuned/profiles/
mv /root/rpmbuild/BUILDROOT/tuned-2.23.0-1.el9.x86_64/usr/lib/tuned/profiles/realtime/realtime-variables.conf \
        /root/rpmbuild/BUILDROOT/tuned-2.23.0-1.el9.x86_64/etc/tuned/realtime-variables.conf
mv /root/rpmbuild/BUILDROOT/tuned-2.23.0-1.el9.x86_64/usr/lib/tuned/profiles/realtime-virtual-guest/realtime-virtual-guest-variables.conf \
        /root/rpmbuild/BUILDROOT/tuned-2.23.0-1.el9.x86_64/etc/tuned/realtime-virtual-guest-variables.conf
mv /root/rpmbuild/BUILDROOT/tuned-2.23.0-1.el9.x86_64/usr/lib/tuned/profiles/realtime-virtual-host/realtime-virtual-host-variables.conf \
        /root/rpmbuild/BUILDROOT/tuned-2.23.0-1.el9.x86_64/etc/tuned/realtime-virtual-host-variables.conf
mv /root/rpmbuild/BUILDROOT/tuned-2.23.0-1.el9.x86_64/usr/lib/tuned/profiles/cpu-partitioning/cpu-partitioning-variables.conf \
        /root/rpmbuild/BUILDROOT/tuned-2.23.0-1.el9.x86_64/etc/tuned/cpu-partitioning-variables.conf
mv /root/rpmbuild/BUILDROOT/tuned-2.23.0-1.el9.x86_64/usr/lib/tuned/profiles/cpu-partitioning-powersave/cpu-partitioning-powersave-variables.conf \
        /root/rpmbuild/BUILDROOT/tuned-2.23.0-1.el9.x86_64/etc/tuned/cpu-partitioning-powersave-variables.conf
install -pm 0644 recommend.conf /root/rpmbuild/BUILDROOT/tuned-2.23.0-1.el9.x86_64/usr/lib/tuned/recommend.d/50-tuned.conf
# bash functions used by profile scripts
install -Dpm 0644 functions /root/rpmbuild/BUILDROOT/tuned-2.23.0-1.el9.x86_64/usr/lib/tuned
install: cannot stat 'functions': No such file or directory
make[1]: *** [Makefile:172: install] Error 1
make[1]: Leaving directory '/root/rpmbuild/BUILD/tuned-2.23.0'
error: Bad exit status from /var/tmp/rpm-tmp.owCTCq (%install)
```

I'll try to see why tomorrow.

**Comment by zacikpa** [comment]
@jmencak That looks as if the change which moves the `functions` file from `/profiles` to `/` hasn't been applied. How are you testing this?

**Comment by jmencak** [comment]
> @jmencak That looks as if the change which moves the `functions` file from `/profiles` to `/` (the root directory of this repository) hasn't been applied. How are you testing this?

I just clone the repo and run `make rpm` on RHEL 9.2.

With the commit 8143d2c7 the build works fine.

**Pull request merged**
