### PR TITLE
syspurpose is provides by subscription-manager on RHEL-9

### PR DESCRIPTION
**Pull request by yarda**
Signed-off-by: Jaroslav Škarvada <jskarvad@redhat.com>

### CODE REVIEW

**Review by CZerta — APPROVED** [review]
Seems ok

**Comment by nullr0ute** [comment]
What does syspurpose do? We don't ship subscription-manager in RHEL 4 Edge and this now pulls in the entire subscription-manager/dnf stack which we don't use at all for edge.

**Comment by nullr0ute** [comment]
Looking at the code this module is optional so can we at least have it as a recommends as opposed to a hard requires?

**Comment by yarda** [comment]
> What does syspurpose do? We don't ship subscription-manager in RHEL 4 Edge and this now pulls in the entire subscription-manager/dnf stack which we don't use at all for edge.

It's used for autodetection whether machine is desktop/workstation and then the default TuneD profile is selected accordingly.

**Comment by yarda** [comment]
> Looking at the code this module is optional so can we at least have it as a recommends as opposed to a hard requires?

Recommends should work. I will open PR for it.

**Pull request merged**
