### PR TITLE
Avoid unnecessary inter-processor interrupts by checking that writes are necessary

### PR DESCRIPTION
**Pull request by zacikpa**
This PR adds a new option `check_diff` to the function `commands.write_to_file`. When set to `True`, the function checks whether the current value is equal to the one being written - if it is, the write is skipped.

The new option is disabled by default, but I enable it for plugin options where the write may cause an inter-processor interrupt even when the value does not change.

### CODE REVIEW

**Review by jmencak — COMMENTED** [review]
Thank you for the PR. I'm wondering why do we need a new option for this and why this is not a default? cc @MarSik

**Comment by jmencak** [comment]
Thank you for the PR, @zacikpa . Testing this right now. So far, I've noticed the following issues.  When the same value is in the governor, we still write the same value.  The `check_diff` seems to be `False`.  Another issue I've noticed is that we'll need to change the TuneD configs.  There are some aliases like "performance" when written to `/sys/devices/system/cpu/cpuX/power/energy_perf_bias` will be translated to `0`.  So our configuration, such as 

```
energy_perf_bias=performance
```

will have to be changed to

```
energy_perf_bias=0
```
so that we take advantage of this new functionality.

Anyways, could you please look into the `scaling_governor` issue?  Thank you.

**Comment by jmencak** [comment]
Also, running

```
x86_energy_perf_policy -r
```

causes quite a few IPIs.  This is pretty "expensive" if we're just checking that `x86_energy_perf_policy` is supported by `TuneD` and then we never use it anyway.  I wonder if we could just check for the presence of the file and whether it is executable?

**Comment by jmencak** [comment]
I've finished testing the code.  In summary, I see these issues that I'd like to see fixed before merging:
* setting the same `scaling_governor` still triggers IPIs
* let's remove `x86_energy_perf_policy -r` check, which causes unnecessary IPIs

Issues that I do not expected fixed by this PR:
* `[rtentsk]` plug-in
* even `reading` EPP/EPB causes IPIs

**Comment by zacikpa** [comment]
Hello @jmencak. I updated the PR so that:

- `check_diff` is `True` also for the `scaling_governor`,
- `x86_energy_perf_policy` is only checked for if we may actually need it, i.e., if we cannot set EPB via sysfs.  

Regarding the reads: if reading EPP is as expensive as writing, then I'd say it doesn't make sense to check the value first.

**Comment by zacikpa** [comment]
@jmencak Regarding the aliases for EPB: can you please open a separate upstream or Jira issue for that?

**Comment by jmencak** [comment]
Thank you for the changes, Pavol.  Great work!  The code now does what I expect it to do.  After testing, I can only see IPIs caused by the following options:

```
[rtentsk]
[cpu]
energy_perf_bias=<value>
energy_performance_preference=<value>
```

At this point this is expected and hard to avoid/work around.

The code changes look sane to me, but deferring to other reviewers for comment.

**Review by yarda — COMMENTED** [review]
Thanks, the code LGTM. I have two minor comments that aren't blockers and could be handled later. I think this PR needs to be merged into FDP and we have still some time to fine tune it, so I will keep it open for now.

**Review by yarda — APPROVED** [review]

**Pull request merged**
