### PR TITLE
Fix a hang on SIGHUP when the preset profile does not exist

### PR DESCRIPTION
**Pull request by olysonek**
Please take a look at the second commit. The `return False` when the daemon is not running has been there for ages, however I'm not sure if it serves a specific purpose. Do you think we can drop it?

### CODE REVIEW

**Comment by olysonek** [comment]
I need to think this through. Please don't merge.

**Comment by olysonek** [comment]
@yarda I'm happy with this now. Can you please review?

**Comment by olysonek** [comment]
@jmencak It would be great if you could test it.

**Comment by jmencak** [comment]
I can no longer reproduce the "hang" with this patch.  Thank you!

**Comment by yarda** [comment]
@olysonek thanks for the patch and @jmencak thanks for testing, merging.

**Pull request merged**
