### PR TITLE
plugin_net: do not read monitors if dynamic tuning is disabled

### PR DESCRIPTION
**Pull request by yarda**
Resolves: RHEL-28757

### CODE REVIEW

**Review by zacikpa — APPROVED** [review]
I  guess this is OK as a quick fix, but similar issues may come up in the disk plugin and the load plugin, which also use monitors.

**Comment by yarda** [comment]
> I guess this is OK as a quick fix, but similar issues may come up in the disk plugin and the load plugin, which also use monitors.

Thanks, it's a good point, I will improve the PR.

**Comment by yarda** [comment]
I added `_instance_init_dynamic` base plugin method and did all the dynamic tuning initialization there.

**Comment by yarda** [comment]
Although the other plugins shouldn't pose problem, I think it's more clean now.

**Review by zacikpa — COMMENTED** [review]
Looks good, thanks!

**Pull request merged**
