### PR TITLE
Rt entsk plugin

### PR DESCRIPTION
**Pull request by yarda**

### CODE REVIEW

**Comment by jmencak** [comment]
This won't work.  The `plugin_rtentsk.py` is being created in a wrong directory.  You probably want to put it in `/tuned/plugins` (/tuned) is missing from the path.  `s|b/plugins/plugin_rtentsk.py|b/tuned/plugins/plugin_rtentsk.py|`

**Comment by yarda** [comment]
> This won't work. The `plugin_rtentsk.py` is being created in a wrong directory. You probably want to put it in `/tuned/plugins` (/tuned) is missing from the path. `s|b/plugins/plugin_rtentsk.py|b/tuned/plugins/plugin_rtentsk.py|`

Thanks, it should be fixed now.

I have just converted the patches from Marcelo to PR. I didn't do any check on them.

**Comment by jmencak** [comment]
Thanks, Jardo, this works and matches the functionality of the old rt-entsk daemon with respect
to setting socket timestamping.

Using ftrace I was able to isolate the action of the plugin at the plugin start:

```
           tuned-1404  [000] ....  1226.197142: net_enable_timestamp <-sock_setsockopt
     kworker/0:1-1387  [000] ....  1226.197146: static_key_enable <-process_one_work
         chronyd-1411  [001] ....  1229.203121: net_enable_timestamp <-sock_setsockopt
```

and at the plugin stop:

```
           tuned-1404  [000] ....  1339.469823: net_disable_timestamp <-__sk_destruct
     kworker/0:0-1418  [000] ....  1339.469916: static_key_disable <-process_one_work
         chronyd-1411  [001] ....  1339.582314: net_enable_timestamp <-sock_setsockopt
```

**Comment by jmencak** [comment]
Thank you for the PR.  Can this be merged?
/lgtm

**Comment by yarda** [comment]
> Thank you for the PR. Can this be merged?
> /lgtm

OK, taking this as a positive review, merging.

**Pull request merged**
