### PR TITLE
mssql: update profile to be in sync with MS recommendations

### PR DESCRIPTION
**Pull request by yarda**
Resolves: rhbz#1942733

Signed-off-by: Jaroslav Škarvada <jskarvad@redhat.com>

### CODE REVIEW

**Review by CZerta — CHANGES_REQUESTED** [review]
Missing line "kernel.sched_migration_cost_ns=500000" from BZ? Also different summary, but it's probably not important.

**Comment by yarda** [comment]
> Missing line "kernel.sched_migration_cost_ns=500000" from BZ? Also different summary, but it's probably not important.

Good catch. It was set only on the AMD, but it should be set everywhere, I will update the PR.

**Comment by yarda** [comment]
I also changed the summary, using 'Microsoft' instead of the 'MS' seems better to me.

**Review by CZerta — APPROVED** [review]
Seems ok

**Pull request merged**
