### PR TITLE
uncore: Allow to configure frequency limits using percent

### PR DESCRIPTION
**Pull request by sgruszka**
Using direct frequency values in only useful in specialistic profiles
where we know target platform. Allow to configure uncore frequency as
percent of hardware maximum/minimum frequency. Such parameters can be
used in generic profiles like 'balanced' in portable way, for example:

[uncore]
max_freq_khz=90%

### CODE REVIEW

**Review by yarda — CHANGES_REQUESTED** [review]
Please add ASCII doc inline comments describing plugin parameters like other plugins have. Especially mention what happened in case of conflicting setting (i.e. khZ vs percentage).

Otherwise the code LGTM.

**Comment by yarda** [comment]
What about using unit suffix to distinguish between percentage and kHz? Then we could avoid the possible conflict between kHz and percentage setting. E.g. we used something similar in `readahead` option of disk plugin, where the user can set the value in sectors or kiBs.

**Comment by sgruszka** [comment]
> What about using unit suffix to distinguish between percentage and kHz? Then we could avoid the possible conflict between kHz and percentage setting. E.g. we used something similar in `readahead` option of disk plugin, where the user can set the value in sectors or kiBs.

Sorry  for delay, I was busy with other project. Yes, suffix makes perfect sense, will update.

**Comment by sgruszka** [comment]
@yarda I made the update, please check.  Not sure why test are failing now, I think it's issue with CI.

**Review by yarda — APPROVED** [review]
LGTM, the CI failure is unrelated.

**Pull request merged**
