### PR TITLE
[Docs] Improved the description of the script plug-in

### PR DESCRIPTION
**Pull request by mrksu**
This PR fixes https://bugzilla.redhat.com/show_bug.cgi?id=1671107

### CODE REVIEW

**Comment by mrksu** [comment]
Sorry about the force pushes on my branches. I added more commits and squashed them afterwards -- nothing scary happening.

**Comment by olysonek** [comment]
No problem, that is the correct way to do it. The changes look good. It's much better now, thanks! I'll let Jarda merge it.

**Comment by yarda** [comment]
@mrksu please update the script description, that it can be any executable/script, e.g. Bash script

**Comment by olysonek** [comment]
You mean this, right? "Can be used for the execution of an external Bash script"
Agreed.

(I thought that there was some magic happening inside the `process` function in the Bash library, but I was wrong.)

**Comment by olysonek** [comment]
Well, there is no magic, however importing the Bash library does bring some useful variables, such as `STORAGE_PERSISTENT`. That's why I think Bash scripts are preferable...

**Comment by mrksu** [comment]
OK, I've generalized the text to say that you can run an "executable", which can be either a "script" or a "binary". The parts about Bash scripts specifically say Bash.

**Comment by yarda** [comment]
Thanks, merged.

**Pull request merged**
