### PR TITLE
Recommend.d functionality

### PR DESCRIPTION
**Pull request by olysonek**

### CODE REVIEW

**Comment by olysonek** [comment]
I changed the last commit implementing the recommend.d feature according to our discussion.

**Comment by yarda** [comment]
Thanks, merged.

**Comment by yarda** [comment]
I will just rename the 50-tuned-recommend.conf to 50-tuned.conf. I think it's enough and self-explanatory.

**Comment by yarda** [comment]
Commit renaming the file: https://github.com/redhat-performance/tuned/commit/79e519784b98695378ce6221770a99de91c1fe53

**Pull request merged**
