### PR TITLE
Drop sap-hana-vmware profile, fix other SAP profiles

### PR DESCRIPTION
**Pull request by olysonek**
Please don't merge yet.

Resolves: rhbz#1708418
Resolves: rhbz#1701394

### CODE REVIEW

**Comment by olysonek** [comment]
Resolves: rhbz#1715541

**Comment by olysonek** [comment]
> Please don't merge yet.

I marked this PR as work-in-progress because I'm not sure whether we should change the value of `kernel.sem` in the `sap-hana` profile - I'm waiting for response to https://bugzilla.redhat.com/show_bug.cgi?id=1701394#c10. However I think it's likely that the change is supposed to be done in `sap-hana`, so I added the change to this PR. We can revert it later, if needed, however I don't think that it will be needed.

I propose we merge this now.

**Comment by olysonek** [comment]
I've received confirmation that the change also applies to `sap-hana`, so this PR can be merged as it is. https://bugzilla.redhat.com/show_bug.cgi?id=1701394#c13

**Comment by yarda** [comment]
LGTM, thanks, merged.

**Pull request merged**
